### ISSUE TITLE
GDB and sanitizer support

### ISSUE THREAD

**Issue by EinarElen** [LDMX-Software/docker#39]
## Is your request related to a problem? Please describe.
See https://github.com/LDMX-Software/ldmx-sw/issues/1043

## Describe the solution you'd like. What packages do you want installed?
`gdb` and `libasan4-dbg`

Note that I believe the dbg package is needed if you want to get better symbols in the output from the sanitizers. 

**The Development Container is based on Ubuntu 18.04. How do you install your necessary packages on Ubuntu?**
A description and list of commands to run, for example
```
apt-get install gdb libasan4-dbg
```

**Comment by tomeichlersmith** [comment]
Since both of these packages seem to be in the Ubuntu 18.04 (bionic) repos, adding them to the container should be as easy as putting them into newlines in the Dockerfile:

https://github.com/LDMX-Software/docker/blob/13eaf9ae1b9fb1118098ab0c61383d80ee52f40c/Dockerfile#L6-L46

I've been keeping the packages in alphabetical order and on new lines just to keep myself organized. I've also been keeping the list of them up-to-date in a [markdown file](https://github.com/LDMX-Software/docker/blob/main/docs/ubuntu-packages.md) so all of the ones that are included have a specific reason. I have left some that I have removed in the packages documentation for future debugging purposes.

**Comment by EinarElen** [comment]
Hi again, 

b4ab9b9e2b729cc37916fc1807c84fe1d742ce44 and e90ec074e087597f590207419955b6601c9d4d85 from https://github.com/LDMX-Software/docker/compare/einarelen-dev should contain those additions for both the Dockerfile and the markdown file. Is there anything else that needs to be done or can I go ahead and open a pull request?

**Comment by tomeichlersmith** [comment]
Go ahead and open a PR, the GitHub actions check the basics for us (e.g. the the image builds and it can build ldmx-sw/trunk)

**Comment by EinarElen** [comment]
Super!
